### ISSUE TITLE
Getting "ext_session_lock_surface_v1@21: error 0: session lock surface has never been configured" after shutting down while locked

### ISSUE THREAD

**Issue by vmaggioli** [mortie/swaylock-effects#103]
When I was attempting to unlock my correct password wasn't being accepted, so I restarted my computer in order to get back in. After rebooting anytime I try to run `swaylock` I get the following error:
`ext_session_lock_surface_v1@21: error 0: session lock surface has never been configured`.

I'm assuming some resource is still locked since I shut down while the screen was locked - any suggestions on what to try?

**Comment by rmburg** [comment]
Same issue here. Interestingly, the normal swaylock package works fine.

**Comment by thyeun** [comment]
Everyone, if you are using arch linux, try to using the git version, actually it is an upgrade from `swaylock-effects-git r402.9ac172a-1` to `swaylock-effects-git r416.xxxxxx-1`  if you re-install swaylock-effects-git again.

it solve the issue `ext_session_lock_surface_v1@21: error 0: session lock surface has never been configured` but i'm not sure this version will solve the red screen of death or not. (i facing red screen of death also)

**Comment by vmaggioli** [comment]
@thyeun  This solved my problem, and I'm not currently facing the red screen of death either. Thank you!
