### ISSUE TITLE
 swaylock --grace 2  --> lets you in without any password even after 2 sec 

### ISSUE THREAD

**Issue by nirmoy** [mortie/swaylock-effects#20]

**Comment by mortie** [comment]
Hmm, I can't reproduce this. When I run `swaylock --grace 2`, hitting a key (or moving the mouse, hitting the touch screen, ...) before 2 seconds have passed exits swaylock , but after 2 seconds have passed, a password is required.

What's the exact command are you running?

**Comment by MatthiasCoppens** [comment]
I can't know for sure whether OP is describing this issue, but when you suspend the machine less than 2 secs after locking it, your machine will not ask for a password when unlocking.

**Comment by nirmoy** [comment]
Sorry I did not explain it nicely and because of that I forgot the whole issue. I can't reproduce any issue with above command. Sorry about that noise.
