### ISSUE TITLE
Errors with source build

### ISSUE THREAD

**Issue by vincit-haihala** [mortie/swaylock-effects#59]
Built from source because [this](https://github.com/mortie/swaylock-effects/issues/57) said that would fix the inversion issue. Every time I try to run swaylock-effects I get an error in red saying `[shadow.c:18] swaylock needs to be setuid to read /etc/shadow`. If I run swaylock as root(shouldn't need it, but just in case), I get a different error saying `[shadow.c:36] Unable to drop root (we shouldn't be able to restore it after setuid): Success`

**Comment by vincit-haihala** [comment]
`sudo chmod a+s /usr/local/bin/swaylock` fixed the issue. I originally didn't run it because I did install pam and the build instructions say that this is required "On systems without PAM, you need to suid the swaylock binary" and I did install PAM through dnf. I guess I should've installed pam-devel.

Can confirm that building from source fixes the issue of the screenshot being flipped upside down.

**Comment by ignamartinoli** [comment]
I was having the same issue, I only received the first message. I'm running the ebuild from **Gentoo** **GURU**. I don't have anything in `/usr/local/bin/swaylock`, but after running `doas chmod a+s /usr/bin/swaylock`, I began receiving the second message about being unable to drop root. How can I fix this?
