### ISSUE TITLE
Feature Request: Custom clock format string

### ISSUE THREAD

**Issue by rYR79435** [mortie/swaylock-effects#61]
In the same way `date` accepts a format string.
I _think_ currently it is based on the locale. Would it be possible to set a specific "locale" just for the clock?

**Comment by gavinbeatty** [comment]
The README says:

* `--clock` to show date/time in the indicator
    * Use `--indicator` to make the indicator always active
    * Use `--timestr` and `--datestr` to set the date/time formats (using strftime-style formatting)

You probably just don't have these in your distribution's package yet, and are
waiting on #63.

**Comment by rYR79435** [comment]
Huh. I completely missed that.
RTFM to me..
