### ISSUE TITLE
Linking error using clang

### ISSUE THREAD

**Issue by z4rcher** [mortie/swaylock-effects#7]
The error I'm getting when trying to build with ninja:

`[1/1] Linking target swaylock.
FAILED: swaylock 
/usr/bin/clang  -o swaylock 'swaylock@exe/background-ima
ge.c.o' 'swaylock@exe/cairo.c.o' 'swaylock@exe/comm.c.o'
 'swaylock@exe/log.c.o' 'swaylock@exe/loop.c.o' 'swayloc
k@exe/main.c.o' 'swaylock@exe/password.c.o' 'swaylock@ex
e/pool-buffer.c.o' 'swaylock@exe/render.c.o' 'swaylock@e
xe/seat.c.o' 'swaylock@exe/unicode.c.o' 'swaylock@exe/ef
fects.c.o' 'swaylock@exe/pam.c.o' -Wl,--no-undefined -Wl
,--as-needed -fopenmp -flto -Wl,--start-group libclient_
protos.a /usr/lib64/libcairo.so /usr/lib64/libgdk_pixbuf
-2.0.so /usr/lib64/libgobject-2.0.so /usr/lib64/libglib-
2.0.so -lm -lrt -ldl /usr/lib64/libxkbcommon.so /usr/lib
64/libwayland-client.so -lpam -Wl,--end-group '-Wl,-rpat
h,$ORIGIN/' -Wl,-rpath-link,/home/z4rcher/swaylock-effects/
build/
/usr/bin/ld: libclient_protos.a: error adding symbols: a
rchive has no index; run ranlib to add one` 

And trying to build index using ranlib I got:
`ranlib: libclient_protos.a: no archive map to update`

**Comment by z4rcher** [comment]
Ok, looking further into the issue:
`nm: meson-generated_xdg-shell-protocol.c.o: file format not recognized
nm: meson-generated_xdg-output-unstable-v1-protocol.c.o: file format not recognized
nm: meson-generated_wlr-layer-shell-unstable-v1-protocol.c.o: file format not recognized
nm: meson-generated_wlr-input-inhibitor-unstable-v1-protocol.c.o: file format not recognized
nm: meson-generated_wlr-screencopy-unstable-v1-protocol.c.o: file format not recognized`

Any idea what source files are needed to recompile these?

**Comment by mortie** [comment]
I haven't seen that before, but it doesn't look like it's necessarily related to anything I've done in swaylock-effects. Can you see if you can compile the regular [swaylock](https://github.com/swaywm/swaylock)?

**Comment by z4rcher** [comment]
> Can you see if you can compile the regular [swaylock](https://github.com/swaywm/swaylock)?

Yes and linking finished successfully:
`[30/30] Linking target swaylock.`

The only additional requirement by your fork is **openmp**, have you added the required flags like `-fopenmp` to be passed to clang?

**Comment by mortie** [comment]
Yeah, those flags should already be passed in. I have also compiled it successfully with clang before, which is why I know clang needs openmp when gcc doesn't (since it's built in to gcc).

Could you give me the complete log of a fresh build? Something like `rm -r build && (meson build && ninja -C build)
2>&1 > log.txt`

**Comment by z4rcher** [comment]
Sure thing:
[log.txt](https://github.com/mortie/swaylock-effects/files/3461308/log.txt)

**Comment by mortie** [comment]
I created a Fedora VM and played around with it; it turns out there's an issue with using link-time optimization when using static libraries and clang.

https://github.com/mortie/swaylock-effects/commit/6f29f07654b289e870ffb0c619410c2f09c9259b should fix it by just disabling LTO.

**Comment by z4rcher** [comment]
I can confirm it works now. In the future, please add /etc/pam.d/swaylock containing `auth include login` to the files to be installed when **pam** is detected.

Thanks for everything
