### ISSUE TITLE
Release Tags

### ISSUE THREAD

**Issue by travankor** [mortie/swaylock-effects#8]
Currently, it seems like swaylock-effects is using swaylock's git tags with the effects patches rebased on top of the last release.

Could you have separate release tags so that we can package this outside of the AUR?

Thanks.

**Comment by maxice8** [comment]
+1, I want to package this on Alpine Linux and fetching from git instead of release tarballs is frowned upon.

**Comment by mortie** [comment]
Hi, sorry it has been so long. I merged in upstream's v1.6, and released v1.6-0: https://github.com/mortie/swaylock-effects/releases/tag/v1.6-0

If you have published packages and released them somewhere, and you want them in the "From Packages" section in the readme, send me the link and I'll add them.

**Comment by travankor** [comment]
Nice, but the current released swaylock version technically is 1.5 :P
1.6 is the next version (development HEAD)

**Comment by mortie** [comment]
Oh darn, you're right :p I assumed that the version was reflected by build.meson, but it seems like they update that number at the beginning of a cycle, not at the end.

Oh well, the version of swaylock-effects based on 1.5 will just have to be called 1.6-x.
