### ISSUE TITLE
unrecognized option? ._.

### ISSUE THREAD

**Issue by MaccaAlbarn** [mortie/swaylock-effects#94]
i was very excited to try out swaylock-effects since i was thinking of making a sway rice based of in Serial Experiments Lain, however, while i was testing my config, the fade-in effect didn't show, i checked the outpout and it showed me this
![unknown1670034375_grim](https://user-images.githubusercontent.com/104636370/205418186-ed46b73c-3984-4a59-a23e-1c40fab5c0f2.png)
am i doing something wrong?, if someone needs it, this is how my config looks like (very simple ik, i did it for testing purposes so i could move on and do my definitive config)

![unknown1670034387_grim](https://user-images.githubusercontent.com/104636370/205418268-29b89497-7e06-46c2-add3-93890c857f77.png)

**Comment by mortie** [comment]
What version are you using? (`swaylock --version`)

And does it work if you use `--fade-in 0.2` from the command line rather than in a config file?

**Comment by CactiChameleon9** [comment]
In a config file for swaylock you need to use an equals sign for specific values, not a space:
```
fade-in=0.2
```

See https://github.com/luispabon/sway-dotfiles/blob/master/configs/swaylock/config for a more complicated example

**Comment by MaccaAlbarn** [comment]
> In a config file for swaylock you need to use an equals sign for specific values, not a space:
> 
> ```
> fade-in=0.2
> ```
> 
> See https://github.com/luispabon/sway-dotfiles/blob/master/configs/swaylock/config for a more complicated example

oh, i was wrong then... still, thanks for the help!
