### ISSUE TITLE
swaylock --screenshots does not work.

### ISSUE THREAD

**Issue by vimyumy** [mortie/swaylock-effects#95]
$ swaylock --screenshots 
when i issue this command , does not show screen shot, it just shows me a white screen.
$swaylock -v
swaylock version v1.6.10-4-ga1cf657 (Dec 20 2022, branch 'master')

$uname -a 
Linux arch 6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64 GNU/Linux

$sway -v 
sway version 1.9-dev-fbf9191f (Dec 17 2022, branch 'master')

**Comment by piratkin** [comment]
I have the same problem
```sh
$ swaylock -v
swaylock version 1.6.10

$ uname -a
Linux piratkin 6.1.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 18 Jan 2023 19:54:38 +0000 x86_64 GNU/Linux

$ sway -v
sway version 1.8
```

**Comment by nullawhale** [comment]
I have the same problem

```
$ swaylock -v
swaylock version v1.6.10-1-g4b54b85 (Aug 19 2022, branch 'master')

$ uname -a
Linux nullawhale 6.1.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 14 Jan 2023 13:09:35 +0000 x86_64 GNU/Linux

$ sway -v
sway version 1.8
```

**Comment by mortie** [comment]
I believe you're all using jirutka's fork of swaylock-effects (https://github.com/jirutka/swaylock-effects), that's what the AUR package has been changed to these days. There is no 1.6.10 version in this repo.

**Comment by vimyumy** [comment]
gotcha,  thx alot.
